sudo: false
language: ruby
rvm:
  - 2.1.0

before_script:
  - bundle exec rake db:create db:migrate
  - cp "config/secrets.yml.sample" "config/secrets.yml"
  - bundle exec rake sunspot:solr:start_with_waiting
script:
  - bundle exec rake spec --trace
cache: bundler

